package com.example.bank.application.concern;

public enum QueryType {
    //TODO:: Arrange
    SELECT_ALL, SELECT_BY_ID, SELECT_BANK_ACCOUNTS_BY_USER_ID, SELECT_PAYMENT_BY_BANK_ACCOUNT, SELECT_SAVED_ACCOUNT_BY_USER_ID, SELECT_USER_EMAIL, SELECT_USER_EMAIL_LIKE,
    SELECT_USER_USERNAME, SELECT_USER_USERNAME_LIKE, CHECK_CREDENTIALS, INSERT, DELETE, UPDATE
}
